AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  epix-poc

  Sample SAM Template for epix-poc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 512
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  EPIXAgingFormFunction: # New function for EPIX Aging Form
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: epix-aging-form/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        EPIXAgingForm:
          Type: Api
          Properties:
            Path: /epix-aging-form
            Method: post
      Policies:
        - S3FullAccessPolicy:
            BucketName: epix-aging-form

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
  EPIXAgingFormApi:
    Description: API Gateway endpoint URL for Prod stage for EPIX Aging Form function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/epix-aging-form/"
  EPIXAgingFormFunction:
    Description: EPIX Aging Form Lambda Function ARN
    Value: !GetAtt EPIXAgingFormFunction.Arn
  EPIXAgingFormFunctionIamRole:
    Description: Implicit IAM Role created for EPIX Aging Form function
    Value: !GetAtt EPIXAgingFormFunctionRole.Arn
